### ISSUE TITLE
Minimum Boost requirement?

### ISSUE THREAD

**Issue by TomGoffrey** [sebj101/radiatedPowerPackages#1]
I think, judging by the discussion [here](https://github.com/boostorg/boost_install/pull/19), that use of the keyword `ALL` in `find_package(Boost...)` requires minimum Boost version 1.7.3. Is that your understanding too? If so, `CMakeLists.txt` should be altered to reflect this.

**Comment by sebj101** [comment]
Yep, good spot. Having read the discussions it seems like that keyword is associated with version 1.73 and above. I've pushed the change. Thanks for finding!
